class CliTools < Formula
  head "github.com/oliverisaac/cli-tools", :using => :git
  url "https://github.com/oliverisaac/cli-tools/archive/refs/tags/v1.0.8.tar.gz"
  sha256 "0a34391d88c5bc1125f3468d369da569e3243a57032e6cf0f8c677d74df99c54"

  depends_on "coreutils" 
  depends_on "oliverisaac/tap/koi" 
  depends_on "bash" 
  depends_on "jq" 

  def install
    bin.install "./tab-color"
    bin.install "./colorit"
    bin.install "./tag"
    bin.install "./tgrep"
    bin.install "./interval"
    bin.install "./lword"
    bin.install "./currctx"
    bin.install "./urlencode"
    bin.install "./pbj"
    bin.install "./azclone"
    bin.install "./gen-password"
    bin.install "./vim"
    bin.install "./repo"
    bin.install "./map"
    bin.install "./swag"
    bin.install "./fword"
    bin.install "./azrepo"
    bin.install "./get-secret"
    bin.install "./az-repo-select"
    bin.install "./tagmap"
    bin.install "./k"
    bin.install "./yolo"
    bin.install "./tg"
    bin.install "./currns"
    bin.install "./bb"
    bin.install "./vedit"
    bin.install "./save-secret"
    bin.install "./purr"
    bin.install "./word-password"
    bin.install "./no-color"
    bin.install "./kcreatens"
  end
end
