# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ItermCmd < Formula
  desc "Generate files that contain commands and be cmd-clicked inside iTerm2"
  homepage "https://github.com/oliverisaac/iterm-cmd"
  version "1.0.9"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oliverisaac/iterm-cmd/releases/download/v1.0.9/iterm-cmd_1.0.9_darwin_arm64.tar.gz"
      sha256 "a4b491454826f4164120acf7619309c31e5789eefa3864a0e5f31c6dda8e8efc"

      def install
        bin.install "iterm-cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oliverisaac/iterm-cmd/releases/download/v1.0.9/iterm-cmd_1.0.9_darwin_x86_64.tar.gz"
      sha256 "b72af0054ddfa2463515c1c3ad3eed90677410ecfd94e20022b504ba62de15cf"

      def install
        bin.install "iterm-cmd"
      end
    end
  end
end
