# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ItermCmd < Formula
  desc "Generate files that contain commands and be cmd-clicked inside iTerm2"
  homepage "https://github.com/oliverisaac/iterm-cmd"
  version "1.0.5"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oliverisaac/iterm-cmd/releases/download/v1.0.5/iterm-cmd_1.0.5_darwin_arm64.tar.gz"
      sha256 "cf0f21cc92c0111922828b9e2d389963fd69d9c9b8f987eb94ea590ec6576a7a"

      def install
        bin.install "iterm-cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oliverisaac/iterm-cmd/releases/download/v1.0.5/iterm-cmd_1.0.5_darwin_x86_64.tar.gz"
      sha256 "2f74a45d53edd5aa3881af187daf1b030b12cc25c5ad9ad1c54a45a976572dc3"

      def install
        bin.install "iterm-cmd"
      end
    end
  end
end
