# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koi < Formula
  desc "Kubectl wrapper command"
  homepage "https://github.com/oliverisaac/koi"
  version "0.0.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oliverisaac/koi/releases/download/v0.0.2/koi_0.0.2_darwin_arm64.tar.gz"
      sha256 "631dadf56d9343562852cfea4180d01e076287772f55964fcd9ae7816edbf638"

      def install
        bin.install "koi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oliverisaac/koi/releases/download/v0.0.2/koi_0.0.2_darwin_x86_64.tar.gz"
      sha256 "5c604bbb62b3258cce0aeff6b488a0dc111bb5af2c91c9185d55987b22edb97d"

      def install
        bin.install "koi"
      end
    end
  end
end
