# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koi < Formula
  desc "Kubectl wrapper command"
  homepage "https://github.com/oliverisaac/koi"
  version "0.0.6"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oliverisaac/koi/releases/download/v0.0.6/koi_0.0.6_darwin_arm64.tar.gz"
      sha256 "a9a2fbad03fe5b55127be65ea72021a127bf36fd3b1e0cf286c8538e668da59f"

      def install
        bin.install "koi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oliverisaac/koi/releases/download/v0.0.6/koi_0.0.6_darwin_x86_64.tar.gz"
      sha256 "f3101fef3b0cab16c465a4a46add2e5004292160f502fc119364a804be8e1304"

      def install
        bin.install "koi"
      end
    end
  end
end
