# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgrep < Formula
  desc "Grep command with easy to use templates and automatic escaping of special characters"
  homepage "https://github.com/oliverisaac/tgrep"
  version "0.0.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oliverisaac/tgrep/releases/download/v0.0.2/tgrep_0.0.2_darwin_arm64.tar.gz"
      sha256 "83e8fb788947651a7696596be7a5825fbfa1496f0853a9b204fd0afc29a355db"

      def install
        bin.install "tg"
        bin.install "tgrep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oliverisaac/tgrep/releases/download/v0.0.2/tgrep_0.0.2_darwin_x86_64.tar.gz"
      sha256 "5c894657ab020ff5dc17f0161c81669f5b7e3f34cd10c4a47fe14c8c1a5ca1ea"

      def install
        bin.install "tg"
        bin.install "tgrep"
      end
    end
  end
end
