# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgrep < Formula
  desc "Grep command with easy to use templates and automatic escaping of special characters"
  homepage "https://github.com/oliverisaac/tgrep"
  version "0.0.4"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oliverisaac/tgrep/releases/download/v0.0.4/tgrep_0.0.4_darwin_arm64.tar.gz"
      sha256 "bce7847e265430c722b7f4a01da3d3c17967b176c5cb90133117cbde9838620a"

      def install
        bin.install "tg"
        bin.install "tgrep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oliverisaac/tgrep/releases/download/v0.0.4/tgrep_0.0.4_darwin_x86_64.tar.gz"
      sha256 "9002d893db5696fc90b5630794877ae101887fcb542db03c9970f131558e8913"

      def install
        bin.install "tg"
        bin.install "tgrep"
      end
    end
  end
end
